name = "duckduckgo-ai"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

[dev]
ip = "127.0.0.1"

[vars]
API_KEY = "MzUEBLtiX180L0y04U1D5MfIfL67JklqtMiSybq9mxt5835vvvQQ6rldJ4EF2ryb"

[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "42d18326b4284fb9b6e566abbb39ef64"
